export const productActionType = {
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

    FETCH_PRODUCTS_REQUEST_ID: 'FETCH_PRODUCTS_REQUEST_ID',
    FETCH_PRODUCTS_SUCCESS_ID: 'FETCH_PRODUCTS_SUCCESS_ID',
    FETCH_PRODUCTS_ERROR_ID: 'FETCH_PRODUCTS_ERROR_ID',


}

export const requestProducts = () => ({type: productActionType.FETCH_PRODUCTS_REQUEST})
export const requestProductsById = (id: any) => ({type: productActionType.FETCH_PRODUCTS_REQUEST_ID, payload: id})